const axios = require("axios");

const fetchFoursquareVenues = async (queries, location) => {
  const API_KEY = process.env.FOURSQUARE_API_KEY;
  const fields = 'fsq_id,name,location,categories,distance,link,photos';
  let allVenues = [];

  for (const query of queries) {
    try {
      const response = await axios.get("https://api.foursquare.com/v3/places/search", {
        headers: { Authorization: API_KEY, Accept: "application/json" },
        params: {
          query: query,  // Generated by OpenAI
          fields: fields,
          near: location,
          limit: 10       // Get top 5 results per query
        }
      });

      if (response.data.results) {
        allVenues = [...allVenues, ...response.data.results]; // Combine results
      }
    } catch (error) {
      console.error(`❌ Error fetching venues for query: ${query}`, error.message);
    }
  }

  return allVenues; // Limit total results to 10 venues max
};

const fetchVenuePhotos = async (fsq_id) => {
  const url = `https://api.foursquare.com/v3/places/${fsq_id}/photos`;
  const headers = {
    Accept: "application/json",
    Authorization: process.env.FOURSQUARE_API_KEY
  };

  try {
    const response = await axios.get(url, { headers });
    const photos = response.data;

    // Build direct image URLs
    const photoURLs = photos.slice(0, 5).map(photo =>
      `${photo.prefix}original${photo.suffix}`
    );

    return photoURLs;
  } catch (error) {
    console.error(`❌ Error fetching photos for venue ${fsq_id}:`, error.message);
    return [];
  }
};

// fetch venue details by fsq_id: popularity,stats,hours,rating
const fetchVenueDetails = async (venueId) => {
  const fields = 'fsq_id,popularity,stats,hours,rating,tips';
  try {
    const response = await axios.get(`https://api.foursquare.com/v3/places/${venueId}`, {
      headers: {
        Accept: "application/json",
        Authorization: process.env.FOURSQUARE_API_KEY
      },
      params: {
        fields: fields,
      },
    });
    return response.data;
  }
  catch (error) {
    console.error(`Error fetching venue details for ${venueId}:`, error.message);
    return null;
  };
};

  module.exports = { fetchFoursquareVenues, fetchVenuePhotos, fetchVenueDetails };
