const axios = require("axios");

const fetchFoursquareVenues = async (queries, location) => {
  const API_KEY = process.env.FOURSQUARE_API_KEY;
  const fields = 'fsq_id,name,location,categories,distance,link,photos';
  let allVenues = [];

  for (const query of queries) {
    try {
      const response = await axios.get("https://api.foursquare.com/v3/places/search", {
        headers: { Authorization: API_KEY, Accept: "application/json" },
        params: {
          query: query,  // Generated by OpenAI
          fields: fields,
          near: location,
          limit: 10       // Get top 5 results per query
        }
      });

      if (response.data.results) {
        allVenues = [...allVenues, ...response.data.results]; // Combine results
      }
    } catch (error) {
      console.error(`❌ Error fetching venues for query: ${query}`, error.message);
    }
  }

  return allVenues; // Limit total results to 10 venues max
};


module.exports = { fetchFoursquareVenues };
