const tagsVocabulary = [
    "atm", "beer", "barservice", "businessmeeting", "byo", "clean", "coatcheck",
    "cocktails", "crowded", "datespopular", "delivery", "dressy", "drivethrough",
    "essentialreservations", "familiespopular", "fullbar", "glutenfreediet",
    "goodfordogs", "groupsonlyreservations", "groupspopular", "hasmusic",
    "hasparking", "healthydiet", "jukeboxmusic", "latenight", "livemusic",
    "noisy", "onlinereservations", "outdoorseating", "privatelot", "privateroom",
    "publiclot", "quickbite", "reservations", "restroom", "romantic",
    "servesbarsnacks", "servesbreakfast", "servesbrunch", "servesdessert",
    "servesdinner", "serveshappyhour", "serveslunch", "servestastingmenu",
    "servicequality", "singlespopular", "sitdowndining", "smoking",
    "specialoccasion", "streetparking", "takeout", "takesamex",
    "takescreditcards", "takesdinersclub", "takesdiscover", "takesmastercard",
    "takesnfc", "takesunionpay", "takesvisa", "trendy", "tvs", "valetparking",
    "valueformoney", "vegandiet", "vegetariandiet", "wheelchairaccessible",
    "wifi", "wine", "Reading Fiction or Non-Fiction", "Hiking & Nature Walks",
    "Watching Movies or Series", "Playing Video Games",
    "Attending Live Music Events", "Practicing Yoga or Meditation",
    "Photography", "Painting or Drawing", "Playing Sports (e.g., soccer, tennis)",
    "Cooking or Baking", "Dancing", "Writing or Journaling", "DIY & Crafting",
    "Traveling & Exploring New Places", "Learning Languages",
    "Board Games or Puzzles", "Volunteering or Community Events",
    "Fashion & Styling", "Gardening", "Vegetarian", "Vegan", "Gluten-Free",
    "Halal", "Kosher", "Keto / Low Carb", "Organic / Farm-to-Table",
    "Spicy Food Lover", "Seafood Lover", "Dessert Lover",
    "Asian Cuisine (Chinese, Japanese, Thai)", "Middle Eastern Cuisine",
    "African Cuisine", "Latin American Cuisine", "Indian Cuisine",
    "Fast Food Fan", "Coffee Addict", "Bubble Tea Lover",
    "Street Food Enthusiast", "Cozy / Quiet Places",
    "Artistic / Creative Spaces", "Bookstore Cafes",
    "Historical / Culturally Rich Locations", "Nature / Scenic Spots",
    "Modern & Trendy Spots", "Tech-Friendly Cafes (with Wi-Fi & outlets)",
    "LGBTQ+ Friendly", "Live Music & Jam Nights", "Family-Friendly",
    "Study-Friendly", "Rooftop or Outdoor Seating", "Instagrammable Spots",
    "Pet-Friendly Venues", "Karaoke or Game Nights", "Dance or Music Events",
    "International Cuisine Hotspots", "Local Hidden Gems", "College Student",
    "Working Professional", "Parents with Kids", "Solo Explorer",
    "Young Adults (18-25)", "Adults (26-40)", "Seniors", "Digital Nomad",
    "Couple-Friendly Spots", "Group Hangouts", "First-Date Ideas",
    "Budget-Friendly", "Luxury / Upscale"
  ];
  
module.exports = tagsVocabulary;  