const userToVenueTagMap = {
    
    // 🟣 Hobbies → Venue Tags
    "Reading Books": ["quiet", "bookstore", "wifi"],
    "Hiking & Nature Walks": ["outdoorseating", "nature", "scenic"],
    "Watching Movies / Series": ["wifi", "sitdowndining"],
    "Playing Video Games": ["wifi", "noisy"],
    "Attending Live Music Events": ["livemusic", "hasmusic", "jukeboxmusic"],
    "Practicing Yoga / Meditation": ["quiet", "clean", "romantic"],
    "Photography": ["instagrammable", "scenic", "nature"],
    "Painting / Drawing": ["quiet", "artistic", "bookstore"],
    "Playing Sports": ["groupspopular", "sitdowndining"],
    "Cooking / Baking": ["servesdinner", "servesdessert"],
    "Dancing": ["livemusic", "noisy", "dancefloor"],
    "Writing / Journaling": ["quiet", "wifi", "bookstore"],
    "DIY & Crafting": ["artistic", "quiet"],
    "Traveling / Exploring New Places": ["localgems", "historic", "instagrammable"],
    "Learning Languages": ["quiet", "groupspopular"],
    "Board Games / Puzzles": ["quiet", "groupspopular"],
    "Volunteering / Community Events": ["groupspopular", "restroom"],
    "Fashion & Styling": ["trendy", "dressy"],
    "Gardening": ["outdoorseating", "nature", "scenic"],
  
    // 🟢 Food Preferences → Venue Tags
    "Vegetarian": ["vegetariandiet"],
    "Vegan": ["vegandiet"],
    "Gluten-Free": ["glutenfreediet"],
    "Halal": ["halaldiet"], // custom mapping if available
    "Kosher": ["kosherdiet"],
    "Keto / Low Carb": ["healthydiet"],
    "Organic / Farm-to-Table": ["healthydiet", "valueformoney"],
    "Spicy Food Lover": ["valueformoney", "servesdinner"],
    "Seafood Lover": ["servesdinner"],
    "Dessert Lover": ["servesdessert", "valueformoney"],
    "East Asian Cuisine": ["asian"],
    "Middle Eastern Cuisine": ["middleeastern"],
    "West African Cuisine": ["african"],
    "East African Cuisine": ["african"],
    "Latin American Cuisine": ["latinamerican"],
    "Indian Cuisine": ["indian"],
    "Fast Food Fan": ["quickbite", "takeout"],
    "Coffee Addict": ["wifi", "servesbrunch", "servesdessert"],
    "Bubble Tea Lover": ["servesdessert", "valueformoney"],
    "Street Food Enthusiast": ["takeout", "crowded"],
  
    // 🔵 Thematic Interests → Venue Tags
    "Cozy / Quiet Places": ["quiet", "sitdowndining", "clean"],
    "Artistic / Creative Spaces": ["artistic", "quiet"],
    "Bookstore Cafes": ["quiet", "wifi", "bookstore"],
    "Historical / Culturally Rich Locations": ["historic", "localgems"],
    "Nature / Scenic Spots": ["scenic", "nature", "outdoorseating"],
    "Modern & Trendy Spots": ["trendy", "dressy", "crowded"],
    "Tech-Friendly Cafes (with Wi-Fi & outlets)": ["wifi", "techfriendly"],
    "LGBTQ+ Friendly": ["trendy", "servicequality"],
    "Live Music & Jam Nights": ["livemusic", "hasmusic", "noisy"],
    "Family-Friendly": ["familiespopular", "restroom"],
    "Study-Friendly": ["quiet", "wifi", "sitdowndining"],
    "Rooftop / Outdoor Seating": ["outdoorseating", "scenic"],
    "Instagrammable Spots": ["instagrammable", "scenic"],
    "Pet-Friendly Venues": ["goodfordogs", "outdoorseating"],
    "Karaoke / Game Nights": ["noisy", "jukeboxmusic"],
    "Dance or Music Events": ["livemusic", "dancefloor"],
    "International Cuisine Hotspots": ["servesdinner", "asian", "indian", "latinamerican"],
    "Local Hidden Gems": ["localgems", "valueformoney"],
  
    // 🟠 Lifestyle Preferences → Venue Tags
    "College Student": ["wifi", "quickbite", "budgetfriendly"],
    "Working Professional": ["wifi", "sitdowndining", "reservations"],
    "Parents with Kids": ["familiespopular", "restroom"],
    "Solo Explorer": ["quiet", "valueformoney", "instagrammable"],
    "Young Adults (18–25)": ["trendy", "noisy", "crowded"],
    "Adults (26–40)": ["valueformoney", "romantic"],
    "Midlife Adults (41–60)": ["quiet", "sitdowndining", "romantic"],
    "Seniors": ["quiet", "sitdowndining", "clean"],
    "Digital Nomad": ["wifi", "techfriendly", "outletaccess"],
    "Couple-Friendly Spots": ["romantic", "quiet", "servesdinner"],
    "Group Hangouts": ["groupspopular", "restroom", "sitdowndining"],
    "First-Date Ideas": ["romantic", "quiet", "servesdessert"],
    "Budget-Friendly": ["valueformoney", "quickbite"],
    "Luxury / Upscale": ["valetparking", "servestastingmenu", "dressy"]
};
  

module.exports = userToVenueTagMap;